### PR TITLE
Escape content before `echo`ing them

### PR DESCRIPTION
**Pull request by lmansur**
* afee47f **Set content-type for webhook response**

* 483b6dd **Escape content before `echo`ing them**
  
  The methods used in this commit are:
  * [`esc_attr`][1]: for content that will be used as an HTML attribute
  * [`esc_html`][2]: for content that will be placed inside an HTML tag
  * [`esc_url`][3]: for content that will be used inside URL-related HTML
    attributes, like `src` and `href`
  * [`wp_kses_post`][4]: for content that will be used inside a post (or
    in post-like context)
  * [`intval`][5]: converts values to `int`
  
  https://3.basecamp.com/3293071/buckets/9856127/todos/5621905896
  
  [1]: https://developer.wordpress.org/reference/functions/esc_attr/
  [2]: https://developer.wordpress.org/reference/functions/esc_html/
  [3]: https://developer.wordpress.org/reference/functions/esc_url/
  [4]: https://developer.wordpress.org/reference/functions/wp_kses_post/
  [5]: https://www.php.net/manual/en/function.intval

* cafa6f9 **Revert `intval($member_id)`**
  
  I didn't notice we were already casting to `int` with `(int)`

### CODE REVIEW

**Review by mrhead — APPROVED** [review]
Thanks @lmansur!

Could you please rebase this agains `data-sanitization-and-validation`? I did not realize that you based your branch on mine and I rebased mine against `main`, so this PR shows also changes made in my PR.

**Comment by mrhead** [comment]
Or, if you don't mind, I can rebase it and merge it into my branch, too.

**Comment by lmansur** [comment]
@mrhead done!

**Comment by lmansur** [comment]
@mrhead I think we could keep this open until you merge the base PR tomorrow so the others have a chance to review it separately but I don't feel too strongly.

**Review by jcbpl — APPROVED** [review]

**Review by julianfssen — APPROVED** [review]
Thanks, Lucas! That's a _lot_ of escapes in Wordpress-land 😳

**Comment by mrhead** [comment]
@lmansur I'm going to merge this in, so I can request the plugin review.

**Pull request merged**
