### PR TITLE
Filter post access in Private RSS Feed

### PR DESCRIPTION
**Pull request by lmansur**
https://3.basecamp.com/3293071/buckets/5610905/messages/4565347317

### CODE REVIEW

**Review by mrhead — APPROVED** [review]

**Review by northerner — COMMENTED** [review]
@lmansur Is the intent here to allow any plugin user to define their own memberful_can_user_access_rss_post filter? The default just allows all posts.

**Comment by lmansur** [comment]
> Is the intent here to allow any plugin user to define their own memberful_can_user_access_rss_post filter? The default just allows all posts.

@northerner yep, that's it. We don't want to change the default but allow plugin users to customize the logic if they want to.

**Comment by lmansur** [comment]
@northerner LMK if you have any other thoughts or if it's good to go

**Review by northerner — APPROVED** [review]
Good to go. 👍

**Pull request merged**
