### PR TITLE
Restrict access by custom taxonomies

### PR DESCRIPTION
**Pull request by mrhead**
Previously we supported only categories and post tags. Since this commit
we will support all public taxonomies visible in menu (we use the same
filter for supporting custom post types).

### CODE REVIEW

**Comment by mrhead** [comment]
@lmansur @northerner This is a friendly reminder to review these changes.

Categories and post tags are WordPress core taxonomies. It means that we can use regular taxonomy methods to work with them, and by doing that, we can also support custom taxonomies.

**Review by lmansur — APPROVED** [review]
Sorry for the delay! LGTM

**Comment by mrhead** [comment]
Thanks, @lmansur.

**Comment by northerner** [comment]
Sorry @mrhead, missed the notification for this. Feel free to ping me on Basecamp next time if you're waiting on a review.

Have not tested out these changes myself, but the code makes sense to me.

**Comment by mrhead** [comment]
No problem, @northerner. I'll ping on Basecamp next time :).

**Pull request merged**
