### PR TITLE
Repairing issue caused by filter affecting blocks

### PR DESCRIPTION
**Pull request by ChaseWPDEV**
Moved the do_blocks filter to later in the process.

### CODE REVIEW

**Comment by ChaseWPDEV** [comment]
The main change is to move the do _blocks filter to a priority 15, instead of 1.

**Comment by lmansur** [comment]
Thanks, @ChaseWPDEV! Could you rebase the PR with `main`, please?

**Comment by ChaseWPDEV** [comment]
@lmansur  Done :)

**Comment by lmansur** [comment]
Thanks!

**Pull request merged**
