### PR TITLE
Update setup instructions

### PR DESCRIPTION
**Pull request by mrhead**
This commit adds more information about running, stopping and destroying Docker containers.

### CODE REVIEW

**Comment by mrhead** [comment]
@northerner @lmansur Please let me know if this looks good to you and feel free to suggest any changes.

I've also tried to replace `docker-compose` with `docker compose`, but it's not clear to me if `docker compose` is available on Linux yet. See https://docs.docker.com/compose/cli-command/ for more details.

**Review by northerner — APPROVED** [review]
Looks good, thanks @mrhead.

**Review by lmansur — APPROVED** [review]
Thanks!

`docker compose` doesn't exist on my CLI

**Comment by mrhead** [comment]
> docker compose doesn't exist on my CLI

Thanks! Let's stick with `docker-compose` for now.

**Pull request merged**
